### PR TITLE
Correct Apache Thrift Content-Type over HTTP

### PR DESCRIPTION
**Pull request by kriskowal**

### CODE REVIEW

**Comment by peter-edge** [comment]
I might be missing something but why not on dev and do 1.15.1?

**Comment by breerly** [comment]
@peter-edge might have the right of it - it looks like we might be fixing existing behavior here.

**Comment by kriskowal** [comment]
Fixed the base for the PR. Was intended to target `dev`. I don’t understand @breerly’s affirmation. Previous behavior was not to set a Content-Type. We shipped a version that adds the Content-Type today, but it’s not the correct Content-Type for Apache Thrift, and we’ve observed Apache Thrift multiplexes its response decoder on the Content-Type. So we’ve gone from broken (but nobody depended on the broken behavior) to broken (but nobody depends on the behavior yet) to fixed with this change (and folks will be welcome to depend on it).

**Comment by peter-edge** [comment]
While we're on this, we should probably update proto for the most commonly-used type. There's no official IANA type for proto, but the consensus seems to be around `application/x-protobuf` after looking through a few links, or making your own. Kubernetes uses `application/vnd.kubernetes.protobuf` but this is a one-off.

So we should maybe change it to one of a few things:

1. `application/x-protobuf`
3. `application/vnd.{rpc,yarpc}.protobuf` (2 combinations there)
2. `application/vnd.{rpc,yarpc}.protobuf.{binary,json}` (4 combinations there, this would mean protobuf responses from json would be this instead of `application/json` which i think is actually not desirable, but this is what thrift does https://www.iana.org/assignments/media-types/application/vnd.apache.thrift.json)

Thoughts?

https://www.iana.org/assignments/media-types/media-types.xhtml (thrift does appear on here, protobuf does not)
https://groups.google.com/forum/#!topic/protobuf/VAoJ-HtgpAI
https://github.com/kubernetes/kubernetes/pull/24539/files
https://developers.google.com/api-client-library/java/google-http-java-client/reference/1.20.0/com/google/api/client/protobuf/ProtocolBuffers

**Pull request merged**
