### PR TITLE
Bump up coverage target

### PR DESCRIPTION
**Pull request by blampe**
We're up to 81.54% now so let's continue to raise the bar.

### CODE REVIEW

**Comment by peter-edge** [comment]
There is little benefit to doing this, it will just cause problems and more
noise in reviews/ignored reviews. For example, the crossdock diffs I just
put up *decreased* coverage, if that had made this go below the target, I
would have gotten a red X that would have been noise and I would have
ignored.

The targets don't help and only hurt in my opinion, they cause problems.
There are very few situations where they won't be ignored, and they'll
cause PRs to not be looked at. I talked to people about this in the chat
room a while ago.

**Comment by bombela** [comment]
Agree with Peter. Its a diminishing return.

**Comment by breerly** [comment]
I hear what y'all are saying, and in general I agree that code coverage in itself is not the right goal.

Code coverage *does* however shine a light on parts of a codebase that are missing behavioral tests. For that reason, I'm onboard with what @blampe is trying to do here.

I suggest a slightly different path:

1. We determine which parts of the codebase are lacking in testing
2. We test those parts, and *then* increase the code coverage limit

I find this path better than "increase to 90%, however you get there" because I don't want to be writing tests for the sake of code coverage alone.

@bombela @peter-edge can you guys get onboard w/ this approach?

**Comment by breerly** [comment]
pinging @akshayjshah, @nomis52, and @abhinav for their thoughts on my previous comment

**Comment by peter-edge** [comment]
I just had a long discussion with Bryce about this, the sum of the argument
is that I don't think having a red X on PRs that decrease code coverage
globally by a small % does anything to help us increase code coverage or
prevent it from being decreased, and unless the floor is close (which is
what will lead to red X's), this check effectively does nothing anyways. I
can copy/paste our convo but the short is this tool imo just hinders us.

**Comment by breerly** [comment]
@peter-edge I don't want that situation either - what I do want is to make sure we dont have large amounts of behavior unverified. Once we *do* verify those parts, it seems reasonable to raise the floor at that point.

**Comment by peter-edge** [comment]
A floor is fine, this automated tool that checks it for each PR is the
problem

**Comment by breerly** [comment]
Discussed offline with @peter-edge - here is how I'd like us to deal with CC.

1. Low code coverage is a symptom of a problem, not a problem in itself. The actual problem is having large areas of behavior unverified. To raise the coverage above 90%, we need to identify which behaviors aren't tested, and write tests. I don't want us writing tests "purely for code coverage" - that leads to tests that exercise code paths but don't verify behavior. Instead, I want to work with @blampe to identify areas of unverified behavior, and spec those out as projects. This will naturally increase code coverage.
2. We need to measure code coverage correctly - this means *only* measuring the production library code that we are shipping to customers. @peter-edge is going to follow up to make sure that this is correct, and we suspect that the code coverage is actually pretty close to 90% already.
3. When the floor and the actual CC are the same, it causes PRs to be marked as X in way that is not very usefull. It basically has the effect of "flapping" most new PRs. Instead, I think it's more practical that we raise the floor in 5% increments, as we improve coverage - this balances keeping high CC as a goal, without flapping every other PR.

Code coverage is a *tool* to help us write higher quality software - let's be pragmatic and apply it in a way that is useful to the engineers writing software in this repo.

**Comment by peter-edge** [comment]
SGTM!

**Pull request closed without merging**
