### PR TITLE
Test examples with cram.

### PR DESCRIPTION
**Pull request by abhinav**
Evaluating cram (https://bitheap.org/cram/) as a way to verify that our examples actually work. Soliciting opinions on whether this is worth doing.

This adds tests for the JSON and Thrift keyvalue examples over both, HTTP and TChannel.

Output of the test target:

```
$ make test-examples
make -C examples
---- Building json ----
cd client; go build
cd server; go build
---- Building thrift ----
cd keyvalue/client; go build
cd keyvalue/server; go build
---- Running tests over http ----
json/json.t: passed
thrift/thrift.t: passed
# Ran 2 tests, 0 skipped, 0 failed.
---- Running tests over tchannel ----
json/json.t: passed
thrift/thrift.t: passed
# Ran 2 tests, 0 skipped, 0 failed.
---- Done ----
```

Sample failure:

```diff
thrift/thrift.t: failed
--- thrift/thrift.t
+++ thrift/thrift.t.err
@@ -18,4 +18,4 @@
   > INPUT
   get "foo" failed: "foo" does not exist
   foo = bar
-  baz = qux
+  baz = qx
# Ran 2 tests, 0 skipped, 1 failed.
```

---
This change is [Review on Reviewable](https://reviewable.io/reviews/yarpc/yarpc-go/71)

### CODE REVIEW

**Comment by abhinav** [comment]
CC @yarpc/golang @yarpc/yarpc

**Comment by blampe** [comment]
This is neat. Big fan of keeping examples honest.

**Comment by prashantv** [comment]
:lgtm: I wish the cram tests could interleave intput/output

---

Reviewed 12 of 12 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yarpc/yarpc-go/71#-:-KCRqZ_D2fd1gMEUip-L:-1197731796)*

**Comment by breerly** [comment]
Useful for other langs?

**Comment by abhinav** [comment]
Yeah we can use cram to test other examples too. These specific tests can't be copied over as-is because to my knowledge, only the Go examples provide that REPL-like interface.

**Pull request merged**
