### PR TITLE
Include/expect YARPC Encoding in HTTP requests

### PR DESCRIPTION
**Pull request by abhinav**
Depends on #51.

### CODE REVIEW

**Comment by abhinav** [comment]
@yarpc/golang @yarpc/yarpc

**Comment by breerly** [comment]
Sure :shipit:

**Comment by breerly** [comment]
You're validating that `Encoding` is sent on the wire? Are we sure we want this?

TBH I'm a bit surprised the Crossdock tests passed:

```

  STATUS |    CLIENT    |          RESPONSE          | BEHAVIOR |    SERVER     
+--------+--------------+----------------------------+----------+--------------+
  PASSED | yarpc-go     | ok - Server said: wpUyNS0  | echo     | yarpc-go      
  PASSED | yarpc-go     | ok - Server said: H63Uzmw  | echo     | yarpc-node    
  PASSED | yarpc-go     | ok - Server said: rZkX5Ls  | echo     | yarpc-java    
  PASSED | yarpc-go     | ok - Server said: J+ZOP7Y  | echo     | yarpc-python  
  PASSED | yarpc-node   | ok - Server said: v9lrx0a  | echo     | yarpc-go      
  PASSED | yarpc-node   | ok - Server said: gzrbl9h  | echo     | yarpc-node    
  PASSED | yarpc-node   | ok - Server said: y8zkio6  | echo     | yarpc-java    
  PASSED | yarpc-node   | ok - Server said: c2i98m1  | echo     | yarpc-python  
  PASSED | yarpc-java   | ok - Server said: 03b9f6c  | echo     | yarpc-go      
  PASSED | yarpc-java   | ok - Server said: dd1f048  | echo     | yarpc-node    
  PASSED | yarpc-java   | ok - Server said: 65fc24a  | echo     | yarpc-java    
  PASSED | yarpc-java   | ok - Server said: 60f9069  | echo     | yarpc-python  
  PASSED | yarpc-python | ok - Server said: yvxiihn  | echo     | yarpc-go      
  PASSED | yarpc-python | ok - Server said: pfyhzsq  | echo     | yarpc-node    
  PASSED | yarpc-python | ok - Server said: vujdfoj  | echo     | yarpc-java    
  PASSED | yarpc-python | ok - Server said: enutlku  | echo     | yarpc-python  
```

fyi until #54 is merged, you'll want to check the results manually ;(

**Comment by abhinav** [comment]
No, the header is optional.

**Comment by breerly** [comment]
lgtm

**Comment by junchaowu** [comment]
@breerly do you want me to uncomment the encoding type code back in java now ?

**Comment by breerly** [comment]
@abhinav @junchaowu @kriskowal 2 options:

A - we get every repo sending and enforcing encoding in a matching branch
B - we start sending encoding in every repo, later adding enforcement if needed

**Comment by junchaowu** [comment]
B

**Comment by breerly** [comment]
I can get behind that - @junchaowu, will you create issues for the repos that are not sending encoding over the wire?

**Comment by junchaowu** [comment]
ok

**Pull request merged**
