### PR TITLE
Use Crossdock V2

### PR DESCRIPTION
**Pull request by breerly**
(so that we know when we broke the test suite or not)

- [x] update to use `crossdock:v2` container
- [x] add python back at `yarpc/yarpc-python:crossdock-v2`
- [x] add node back at `yarpc/yarpc-node:crossdock-v2`
- [x] add java back at `yarpc/yarpc-java:crossdock-v2`

### CODE REVIEW

**Comment by kriskowal** [comment]
:ok:

**Comment by abhinav** [comment]
Reviewed 1 of 5 files at r1.
Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[crossdock/client/client.go, line 32 \[r2\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/54#-KCHfEG8qyzd251rqI0H:-KCHfEG8qyzd251rqI0I:-1328211024) ([raw file](https://github.com/yarpc/yarpc-go/blob/5df919c61827c694875747d9bf392e90d94d5de5/crossdock/client/client.go#L32)):*
Combine related consts

```go
const (
    passed = "passed"
    ...
)
```

---

*[crossdock/client/client.go, line 45 \[r2\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/54#-KCHe_kpeq4nfumMWVGS:-KCHe_kpeq4nfumMWVGT:236773606) ([raw file](https://github.com/yarpc/yarpc-go/blob/5df919c61827c694875747d9bf392e90d94d5de5/crossdock/client/client.go#L45)):*
Nit: Both branches are fairly similar. Consider combining them and branching on what `response` is.


```go
var res response
if err != nil {
    res = response{{...}}
} else {
    res = response{{..}}
}
s, _ := json.Marshal(res)
return string(s)
```

---

*[crossdock/client/client.go, line 45 \[r2\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/54#-KCHf579SFUXHfqZ5Dgi:-KCHf579SFUXHfqZ5Dgj:419444256) ([raw file](https://github.com/yarpc/yarpc-go/blob/5df919c61827c694875747d9bf392e90d94d5de5/crossdock/client/client.go#L45)):*
Also, you need to handle that error. It's probably safe to panic in this case if encoding fails.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yarpc/yarpc-go/54)*

**Comment by abhinav** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yarpc/yarpc-go/54#-:-KCHgegPGvedge609c5E:1417088721)*

**Comment by junchaowu** [comment]
lgtm

**Pull request merged**
