### PR TITLE
buildkite: Switch to dynamic pipeline

### PR DESCRIPTION
**Pull request by abhinav**
BuildKite supports the concept of Dynamic Pipelines. You can read more
about it [here][1] but the gist of it is: You can have a shell script
output the YAML for your pipeline instead of writing it by hand.

[1]: https://buildkite.com/docs/pipelines/defining-steps#dynamic-pipelines

This commit switches us over to a dynamic pipeline that lets us choose
between different pipeline.yml files based on an environment variable.

This change is motivated by the intent to introduce a scheduled job on
the YARPC pipeline that runs a different set of commands than the
default pipeline. Since individual jobs can have extra enviroment
variables specified, the scheduled job will specify a different
YARPC_PIPELINE than the default.

Once this change lands, we need to make the following change to the
pipeline upload step in the BuildKite UI.

```diff
-buildkite-agent pipeline upload
+.buildkite/pipeline.sh | buildkite-agent pipeline upload
```

### CODE REVIEW

**Comment by abhinav** [comment]
(I've made the UI change so that the build succeeds.)

**Comment by abhinav** [comment]
:+1: Thanks for making this happen.

I waned to avoid creating a new pipeline because I wasn't sure if that would
need a new repo. I want to keep this in this repo.

**Comment by KevinGrandon** [comment]
> I waned to avoid creating a new pipeline because I wasn't sure if that would need a new repo. I want to keep this in this repo.

Nope, you can have multiple pipelines for a single repo, and you can turn off automatic triggered builds for those pipelines, and just run scheduled builds. Totally up to you on how you want to slice and dice it though.

**Comment by abhinav** [comment]
Makes sense. I'm okay with leaving it as-is for now since there's not much
difference. We can move it out if we decide to use that pipeline for multiple
repositories.

**Pull request merged**
