### PR TITLE
Rename RPC.Serve() to RPC.Start()

### LINKED ISSUE #24: Rename RPC.serve to start

### PR DESCRIPTION
**Pull request by abhinav**
Resolves #24.

### CODE REVIEW

**Comment by abhinav** [comment]
@yarpc/golang @yarpc/yarpc

**Comment by breerly** [comment]
LGTM. 

Do we want to rename the Inbound's serve method to start? Python's inbound start methods are named `listen`. 

@kriskowal @junchaowu @abhinav what's your opinion here? Let's get all the impls to match.

**Comment by prashantv** [comment]
lgtm

**Comment by breerly** [comment]
@abhinav let's rename your inbounds to use Start instead of Mirror, like node and Python

**Comment by abhinav** [comment]
Done

**Comment by breerly** [comment]
:shipit:

**Pull request merged**
