### PR TITLE
Small protobuf code reorganization

### PR DESCRIPTION
**Pull request by peter-edge**
This just moves some stuff around, this isn't anything new.

### CODE REVIEW

**Comment by vivekrsharma** [comment]
@kriskowal beat me to it!

**Comment by breerly** [comment]
@peter-edge dude, let's not create `util.go` files... instead, lets organize code by what it actually does!

**Comment by peter-edge** [comment]
Choose a better name for that file and I'll be all about it.

I will say though, functions that are used across multiple files, I think
just have a generic name

**Comment by abhinav** [comment]
@peter-edge That util.go file is a jumble. Here are some simple things you can do,

- `getBuffer`, `putBuffer`, and the underlying `sync.Pool` go into `buffer_pool.go`
- `uniqueLowercaseStrings` into `strings.go`
- `unmarshal*` and `marshal*` go into `marshal.go`

Generally speaking, if you're putting things into `util.go` or `common.go`, you can definitely break it up into multiple files.

**Comment by peter-edge** [comment]
I really don't like this, and our naming of files in general. We can
discuss offline - I think naming like this makes it worse.

**Comment by abhinav** [comment]
I don't see how that's worse than util.go. It's about finding things in
obvious places. If I'm looking at a call to function `getBuffer` and want to
see what it does, and I don't have Go-to-definition available, I'll look for
the most obvious place where that function would be defined. The file name
buffer.go or buffer_pool.go makes it *very* obvious that `getBuffer` is
defined in there. util.go tells me that anything and everything could be in
there, I'll just have to look.

**Comment by peter-edge** [comment]
We can discuss next week

**Pull request merged**
