### PR TITLE
Bump ragel to 6.10.

### PR DESCRIPTION
**Pull request by bombela**
This new version of ragel compiles correctly with a modern C++ compiler.
Avoiding overflow cast and fixing some broken stdstream operators.

### CODE REVIEW

**Comment by bombela** [comment]
The protobuf files are not failing linting. `make generate` did produce a different output. So I thought I should include them?

The linting change was for some linter complaint about not using keyed attribute to initialize a couple of structs. It doesn't hurt adding them anyway.

**Comment by bombela** [comment]
`make generate` using docker reverted the noise. I must have ran `make generate` locally before. I confirm that running it outside of docker changes the output. I don't know why at all. Especially since `make generate` compiles its own protoc and so on. The only difference should be the version of GCC.

**Comment by peter-edge** [comment]
@bombela LGTM but note I added the keys in another deeply chained PR for you, can you just revert them here so I don't get into rebase hell over the next two days? :)

**Comment by peter-edge** [comment]
@bombela I fixed this, once it passes CI it'll be ready to merge

**Pull request merged**
