### PR TITLE
Consolidate per-encoding {Req,Res}Metas

### LINKED ISSUE #178: Combine encoding's ReqMeta into a single top-level ReqMeta
Currently, we have 3 different ReqMetas:

- `raw.ReqMeta` 
- `json.ReqMeta`
- `thrift.ReqMeta`

The only difference between the 3 is that `thrift.ReqMeta` does not have a `Procedure` field, since we determine the procedure name based on the idl method they are calling. We chose this path because, in theory, each encoding might have different request metadata. This also makes it really clear that you don't need to set `Procedure` when making Thrift calls.

I'd like to reconsider that position. Maintaining a separate `ReqMeta` object per encoding adds mental overhead, makes it a bit awkward to add additional encodings, and is not the most obvious experience. We've received feedback that this is a bit surprising. 

Instead, I'd like to see a single top-level `yarpc.ReqMeta` and `yarpc.ResMeta` structs:

```go
type ReqMeta struct {
    Context context.Context
    Procedure string
    Headers Headers
    TTL time.Duration
}

type ResMeta struct {
    Headers Headers
}
```

This produces an experience like so:

```go

// raw

resBody, resMeta, err := rawClient.Call(
    yarpc.ReqMeta{
        Procedure: "yolo-raw",
        Context: context.Background(),
        Headers: yarpc.Headers{"bob": "ishome"},
        TTL: time.Second,
    },
    []bytes{"raw bytes yall"},
) 

// thrift
// note we don't provide a Procedure
// that will get written (or overwritten) by the encoding,
// you could even imagine allowing someone to override at the call-site if provided

resBody, resMeta, err := userServiceClient.Search(
    yarpc.ReqMeta{
        Context: context.Background(),
        Headers: yarpc.Headers{"bob": "ishome"},
        TTL: time.Second,
    }, 
    userservice.Filter{FirstName: "bob"},
    userservice.LastUUID("..."),
)

// protobufs (feels same as thrift, except only 1 respBody struct)

resBody, resMeta, err := emailServiceClient.Send(
    yarpc.ReqMeta{
        Context: context.Background(),
        Headers: yarpc.Headers{"bob": "ishome"},
        TTL: time.Second,
    }, 
    emailservice.To{Email: "bob@sacajawea.com", From: "Your Friends"},
)
```

* Every encoding uses the same `ReqMeta`, but has varying request bodies
* Every encoding uses the same `ResMeta`, but has varying response bodies

### PR DESCRIPTION
**Pull request by abhinav**
This change combines the per-encoding `{Req,Res}Meta` objects into directional
top-level `{Req,Res}Meta` interfaces:

-   `ReqMeta`: Server-side inbound request metadata
-   `ResMeta`: Server-side outbound response metadata
-   `CallReqMeta`: Client-side outbound request metadata
-   `CallResMeta`: Client-side inbound response metadata

Note that the users will usually type out only the server-side variants for
their handlers. The inbound variants are read-only. The outbound variants
provide getters and fluid setters. Constructors are provided for the outbound
variants only:

```go
func NewReqMeta(ctx context.Context) CallReqMeta

func NewResMeta(ctx context.Context) ResMeta
```

Client usage:

-   JSON

    ```go
    var resp GetValueResponse
    resMeta, err := jsonClient.Call(
        yarpc.NewReqMeta(ctx).
            Procedure("hello").
            Headers(yarpc.NewHeaders().With("foo", "bar")),
        &GetValueRequest{
            // ...
        },
        &resp,
    )
    ```

-   Thrift

    ```go
    resBody, resMeta, err := keyValueClient.GetValue(
        yarpc.NewReqMeta(ctx).
            Headers(yarpc.NewHeaders().With("foo", "bar")),
        arg1,
        arg2,
        // ..
    )
    ```

Server usage:

-   JSON

    ```go
    func MyHandler(reqMeta yarpc.ReqMeta, reqBody *GetValueRequest) (
        *GetValueResponse, yarpc.ResMeta, error,
    ) {
        // ...

        resMeta := yarpc.NewResMeta(reqMeta.Context()).
            Headers(yarpc.NewHeaders().With("foo", "bar"))
        return &GetValueResponse{...}, resMeta, nil
    }
    ```

-   Thrift

    ```go
    func MyHandler(reqMeta yarpc.ReqMeta, arg1 Arg1Type, arg2 Arg2Type) (
        *MyResponse, yarpc.ResMeta, error,
    ) {
        // ...

        resMeta := yarpc.NewResMeta(reqMeta.Context()).
            Headers(yarpc.NewHeaders().With("foo", "bar"))
        return &MyResponse{...}, resMeta, nil
    }
    ```

The handler signatures are fairly similar. The difference is in the number of arguments accepted by the Thrift method.

---

Resolves #178

Related thriftrw-go change: https://github.com/thriftrw/thriftrw-go/pull/159

---

This PR touches a lot of files. Commits are broken up so that they're individually reviewable. The first commit defines the new API and the remaining commits update different parts of the code to use the new API.

### CODE REVIEW

**Comment by abhinav** [comment]
CC @yarpc/golang

**Comment by breerly** [comment]
Let's make sure @prashantv and @akshayjshah weigh in here about our bending of the naming in our constructors for `ReqMeta()` and `ResMeta()` (aka not calling them `NewReqMeta()` and `NewResMeta()`).

**Comment by prashantv** [comment]
This is pretty cool. I'm fine with not using the `New*` naming. The handler methods look a little strange taking a `yarpc.ReqMetaIn`. Ideally both the handler would expect a `yarpc.ReqMeta` and the outbound would use `yarpc.ReqMeta` to wrap the context + add meta information.

The current implementation seems to favour outbound calls over inbound calls (hides the `ReqMetaOut` name when making calls, so the outbound caller gets the nicer `yarpc.ReqMeta` name). I'm fine with that if that's an explicit decision we've made.

**Comment by breerly** [comment]
I wonder if we can organize the "in" direction shapes into a `handler` package, making the handler look like so:

```go
func MyHandler(reqMeta handler.ReqMeta, arg1 Arg1Type, arg2 Arg2Type) (
    *MyResponse, yarpc.ResMetaOut, error,
) {
    // ...

    resMeta := yarpc.ResMeta(reqMeta.Context()).
        Headers(yarpc.NewHeaders().With("foo", "bar"))
    return &MyResponse{...}, resMeta, nil
}
```

This approach still favors the outbound direction, since those shapes live in the `yarpc` package.

**Comment by breerly** [comment]
On second thought, I'm not sold that we should have different shapes for `in/out`. Sure this will allow the shapes to diverge, and we can add properties like `Service` and `Encoding` to the `ReqMetaIn`, but I think it hampers the experience.

With singular `ReqMeta/ResMeta` objects:

* Unit testing is trivial - I can call a handler directly the same way I would call it over the wire, I don't have to punch additional properties or use a separate meta object. 
* The experience is least surprising - the symmetry between the outbound and inbound would be well received by the user.
* I'm not sure these additional properties add any value - it seems likely that if you need access to these transport properties, then you should be building a middleware that has access tot hem.

I think we should consider at least starting with single objects, and live with that for a little bit.

**Comment by prashantv** [comment]
The symmetry is really nice.

Is there any fields on the meta structs that we do want to expose differently on the inbound vs outbound? E.g. something like `CallerName`, where we want to let the inbound get the value, but the outbound should not be able to set the value? We can still do this by just ignoring any value the caller sets in the outbound.

As long as the types and semantics are the same for inbounds and outbounds for all fields we expect on the `ReqMeta`/`ResMeta`, then single object does seem like a simpler solution.

**Comment by abhinav** [comment]
> I'm not sure these additional properties add any value - it seems likely that if you need access to these transport properties, then you should be building a middleware that has access tot hem.

An example of a case where we've already needed access to these properties is the phone procedure. Phone and other forwarding procedures need to know the name of 

> I think we should consider at least starting with single objects, and live with that for a little bit.

We can't start with a single object and change to multiple objects later. We can't switch between these two easily.

---

We can disable setting on the outbounds simply by simply not providing setters.

I guess the primary issue with having a single `ReqMeta` object is that it has these methods `Service()`, `Caller()`, `Encoding()` that will be filled on receipt in a handler but not when you call `yarpc.NewReqMeta(ctx)` because there's no way to set them.

So, in the outbound case,

```go
reqMeta := yarpc.NewReqMeta(ctx).SetProcedure("foo")
reqMetar.Caller() // returns "" and there's no way to change that
```

Inbounds,

```go
func MyHandler(reqMeta yarpc.ReqMeta, reqBody *Something) (*SomethingElse, yarpc.ResMeta, error) {
    reqMeta.Caller() // != ""
    ...
    return &SomethingElse{}, yarpc.NewResMeta(reqMeta.Context()).Headers(...), nil
}
```

We don't have the same problem on inbound vs outbound ResMeta because we don't have any response properties (**yet**) that are available in only one direction.

**Comment by abhinav** [comment]
(Ignore that last message. It was posted accidentally before it was typed out. Proper version incoming.)

**Comment by abhinav** [comment]
@breerly,

-   Being able to call the handler with the same arguments as the client is not
    a hard requirement IMO. Regardless of multiple or single `ReqMeta`, you can
    still unit test handlers by just calling them as functions and providing a
    filled `ReqMeta` object. Needing to punch in more information is necessary
    if your handler behaves differently based on, say, the caller name.
-   Access to these properties is not a rare occurrence. For example, we
    already have people accessing the caller name all the time in TChannel.
    Hiding it at the transport-level API is going to make for an annoying
    experience, especially because there's no easy way to send information from
    the middleware layer to the handler. Sticking it onto the Context might be
    possible, but quite expensive. (Actually, we may eventually want to offer
    some sort of bag-of-values API on `ReqMeta` anyway, but not right now.)
-   We can't change this decision later easily. Whatever we have when we go
    generally available is what we're stuck with.

-------------------------------------------------------------------------------

@prashantv, For `ResMeta`, we don't have any properties (*yet*) that are only
available in one direction. We only have headers on it so far.

For `ReqMeta`,

-   Outgoing, you only have context, headers, and procedure. All are inputs.
-   Incoming, you have context, headers, procedure, service, and caller.
    All read-only. (We currently have encoding too but I think we can drop that
    safely since handlers usually know what encoding they implement; we can add
    it later if necessary.)

Are you suggesting that we have a `ReqMeta` with setters for everything and we
simply ignore everything but context, headers, and procedure in the outbound
case? IMO that makes for a confusing API. We're significantly increasing the
number of parameters we'll ignore if the user sets them. Previously it was just
the procedure, just in the Thrift case.

-------------------------------------------------------------------------------

We *could* have a single `ReqMeta` with setters for headers and procedure
(context is provided when you call `NewReqMeta`) and getters for everything,
with zero values being returned for service and caller in the outbound case.

```go
type ReqMeta interface {
    Context() context.Context
    Headers() yarpc.Headers
    SetHeaders(yarpc.Headers) ReqMeta
    Procedure() string
    SetProcedure(string) ReqMeta
    Service() string
    Caller() string
}

func NewReqMeta(context.Context) ReqMeta { ... }

func foo(ctx context.Context) {
    reqMeta := NewReqMeta(ctx).SetProcedure("foo")
    reqMeta.Procedure() // == "foo"
    reqMeta.Caller()    // == ""
}
```

This still leaves things as, "we don't ignore anything but procedure in the
Thrift case", and the only weirdness it adds is invalid values when you try to
read things you haven't/can't set.

And `ResMeta` again becomes,

```go
type ResMeta interface {
    Context() context.Context
    Headers() yarpc.Headers
    SetHeaders(yarpc.Headers) ReqMeta
}

func NewResMeta(context.Context) ResMeta
```

**Comment by breerly** [comment]
I think I like the following API the best. The user-facing objects get the preferential naming treatment, and the directionally named objects get created within the framework - 

```go
type ReqMeta    interface { .. }  // inbound
type ReqMetaOut interface { .. }  // outbound

type ResMetaIn interface { .. }  // inbound
type ResMeta   interface { .. }  // outbound

func NewReqMeta(ctx) { .. }  // outbound
func NewResMeta(ctx) { .. }  // outbound
```

This creates a user experience like so:

```go
// outbound
resBody, resMeta, err := keyValueClient.GetValue(yarpc.NewReqMeta(ctx), "bob")

// inbound
func MyHandler(reqMeta yarpc.ReqMeta, arg1 Arg1Type, arg2 Arg2Type) (
    *MyResponse, yarpc.ResMeta, error,
) {
    // ...

    resMeta := yrapc.NewResMeta(reqMeta.Context()).
        Headers(yarpc.NewHeaders().With("foo", "bar"))
    return &MyResponse{...}, resMeta, nil
}
```

It *feels* symmetric, but the underlying structs are directional. This will be a big use-ability boost because editors & autocomplete will contain only methods meant to be used, no fluff. Also, no `In/Out` wording facing the user.

The only thing that's tricky about this is calling a handler directly, but we can provide a simplified testing method to create the req meta in for that usecase.

**Comment by abhinav** [comment]
After some thought, I think it might be okay to have slightly inconsistent naming as long as the user facing API is clean. I just renamed and rebased based on @breerly's most recent comment. Is this API agreeable to everyone? (Check the GH PR description for a summary of the API.)

**Comment by breerly** [comment]
lgtm 👍

**Comment by prashantv** [comment]
👍  with the clean names for user facing API and having suffxes for the types that the user does not specify.

When I see `ResMetaIn`, it could mean `ResMeta` on the inbound side (e.g. the handler), or `In` for ResMeta being read. Not sure if there's a less ambiguous name for it. `ResMetaCaller` but that seems a little too specific.

**Comment by abhinav** [comment]
What about `CallResMeta` for `ResMetaIn` and `CallReqMeta` for `ReqMetaOut`?

**Comment by breerly** [comment]
+1 - that's much better

**Comment by prashantv** [comment]
Sure

**Comment by breerly** [comment]
:shipit:

**Pull request merged**
