### PR TITLE
Remove unneeded TODO comment

### PR DESCRIPTION
**Pull request by jkanywhere**
This question was added in a34b22932 on 2017-06-28 and is no longer
relevant. The code has already been released, any breakage has long
since occurred.

- [ ] Description and context for reviewers: one partner, one stranger
- [ ] Docs (package doc)
- [ ] Entry in CHANGELOG.md

### CODE REVIEW

**Review by AllenLuUber — APPROVED** [review]
Thanks for the cleanup!

**Comment by jkanywhere** [comment]
github is showing "buildkite/yarpc-go/pr Pending — Build #3295 blocked"
Is that something I can fix?

**Comment by AllenLuUber** [comment]
> github is showing "buildkite/yarpc-go/pr Pending — Build #3295 blocked"
> Is that something I can fix?

seems the branch is out of date. Can you rebase to the latest `dev`?

**Comment by jkanywhere** [comment]
> Can you rebase to the latest dev?

Done. Now build #3315 is blocked. Progress! 😸

**Comment by Dogild** [comment]
@jkanywhere should be good now!

**Comment by Dogild** [comment]
Merging for you @jkanywhere

**Pull request merged**
