### PR TITLE
Re-add crossdock to code coverage

### PR DESCRIPTION
**Pull request by peter-edge**
This re-adds `internal/crossdock` as part of code coverage. We decided not to ignore test fixtures, they are applicable and we don't want to maintain a whitelist/blacklist of packages for code coverage.

### CODE REVIEW

**Comment by willhug** [comment]
ahh, we're getting the errors from not having _test files in all the directories now.

**Comment by peter-edge** [comment]
Ugh.

Ya, it is, per our convo with @akshayjshah

**Comment by peter-edge** [comment]
Assuming we merge #1073 , can this be approved?

**Comment by peter-edge** [comment]
Done

**Pull request merged**
