### PR TITLE
examples/json: Fix golint/govet warnings

### PR DESCRIPTION
**Pull request by abhinav**

### CODE REVIEW

**Comment by blampe** [comment]
Are we not running these as tests?

**Comment by breerly** [comment]
🚢 

(lets make sure travis is linting these)

**Comment by abhinav** [comment]
We aren't running the linter as part of CI because there's no good way to say 'ignore these files'.

**Comment by breerly** [comment]
or that we lint when `make test` is ran, it should be pretty cheap

**Pull request merged**
