### PR TITLE
gen/proto: Use registered File Descriptors

### PR DESCRIPTION
**Pull request by abhinav**
The code generated by protoc-gen-yarpc-go includes the
FileDescriptorProto of the file and all its dependencies in the
generated code as a `var`. This is the Protobuf representation of the
`.proto` file itself.

As far as I can tell, we are attempting to replicate the behavior of
Protobuf with regards to the contents of this `var`. It's unclear why,
but this has been causing our `make generate` to fail for a month.

The version that protobuf generates includes the following additional
call,

    proto.RegisterFile($fileName, $descriptor)

This is a call to [proto.RegisterFile][1] (or the golang/protobuf
equivalent), which has a corresponding lookup function
[FileDescriptor][2].

  [1]: https://godoc.org/github.com/gogo/protobuf/proto#RegisterFile
  [2]: https://godoc.org/github.com/gogo/protobuf/proto#FileDescriptor

Rather than attempting to replicate the upstream behavior, this change
switches our generated code to rely on the lookup function to populate
our copy of the descriptor.

### CODE REVIEW

**Comment by abhinav** [comment]
Build passed https://uber-open-source-gate.herokuapp.com/buildkite_public_log?https://buildkite.com/uberopensource/yarpc-go/builds/1350 but not reporting to GitHub for some reason. CI Gate appears to be acting up..

**Comment by robbertvanginkel** [comment]
The reason we were writing out the bytes was to make yarpc codegeneration compatible with either `gogo/protobuf` or `golang/protobuf`. 

When using `proto.FileDescriptor()`, it only checks the filedescriptor registry for what `proto` is (the gogo registry in this case). This would break if any proto file in the dependency chain would be registered through an init function that was generated by the go/proto plugin.

Doing it like this was a consious decision to have yarpc be independent of golang/gogo conflicts. How exactly does this this fail `make generate`?

**Comment by abhinav** [comment]
@robbertvanginkel That's unfortunate. And I guess checking both, gogo/protobuf
and golang/protobuf would only be a partial solution because it doesn't
account for other plugins.

The issue is: Over the past month, the automatic dependency update has been
failing because the tests in [this file][1] have been failing because the
expected contents of the descriptor don't match what's in the golden files.

At first I thought that is because the contents of
[testing_no_service.pb.yarpc.go][2] don't match [its golden version][3], and
the contents of [testing.pb.yarpc.go][4] don't match [its golden version][5].
That would make sense because `make generate` doesn't update the golden
version of the files.

However, the test fails even if you update the files manually to match the
output of `make generate`. The version of the descriptor generated by calling
the plugin in the test does not match either version of the .golden file.

[1]: https://github.com/yarpc/yarpc-go/blob/dev/encoding/protobuf/protoc-gen-yarpc-go/internal/testing/testing_test.go
[2]: https://github.com/yarpc/yarpc-go/blob/dev/encoding/protobuf/protoc-gen-yarpc-go/internal/testing/testing_no_service.pb.yarpc.go
[3]: https://github.com/yarpc/yarpc-go/blob/dev/encoding/protobuf/protoc-gen-yarpc-go/internal/testing/testing_no_service.pb.yarpc.go.holden
[4]: https://github.com/yarpc/yarpc-go/blob/dev/encoding/protobuf/protoc-gen-yarpc-go/internal/testing/testing.pb.yarpc.go
[5]: https://github.com/yarpc/yarpc-go/blob/dev/encoding/protobuf/protoc-gen-yarpc-go/internal/testing/testing.pb.yarpc.go.golden

**Comment by abhinav** [comment]
Summary of offline discussion: We're deleting the golden test.

**Pull request closed without merging**
