### PR TITLE
docker: comment the docker logs

### PR DESCRIPTION
**Pull request by vivekrsharma**
This helps debug why docker images aren't get published.

### CODE REVIEW

**Comment by vivekrsharma** [comment]
@breerly @abhinav

**Comment by abhinav** [comment]
https://travis-ci.org/yarpc/yarpc-go/jobs/210672803

Crossdock ran to completion but no push

**Comment by breerly** [comment]
Hmmm... the end of the log is only showing: 

```
Executing Matrix...

..................................................................................[30;1mS[0m[30;1mS[0m[30;1mS[0m.............................................................[30;1mS[0m[30;1mS[0m[30;1mS[0m.[30;1mS[0m[30;1mS[0m[30;1mS[0m.[30;1mS[0m[30;1mS[0m[30;1mS[0m.[30;1mS[0m[30;1mS[0m[30;1mS[0m.[30;1mS[0m[30;1mS[0m[30;1mS[0m.[30;1mS[0m[30;1mS[0m[30;1mS[0m.[30;1mS[0m[30;1mS[0m[30;1mS[0m.[30;1mS[0m[30;1mS[0m[30;1mS[0m.[30;1mS[0m[30;1mS[0m[30;1mS[0m.[30;1mS[0m[30;1mS[0m[30;1mS[0m.[30;1mS[0m[30;1mS[0m[30;1mS[0m.[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m.........................[30;1mS[0m[30;1mS[0m.[30;1mS[0m[30;1mS[0m.[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m.[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m[30;1mS[0m

1027/1027 passed (259/1286 skipped)

Tests passed!

[0m
```

https://s3.amazonaws.com/archive.travis-ci.org/jobs/210672803/log.txt

AFAICT the after success block isn't even executing.

**Comment by abhinav** [comment]
Ah I see the problem

https://github.com/yarpc/yarpc-go/blob/dev/.travis.yml#L93

**Comment by breerly** [comment]
Aaah, looks like we should only exit if status code != 0

**Comment by abhinav** [comment]
Not necessary now that we have the root cause. I'll fix this.

**Pull request closed without merging**
