### PR TITLE
Create end-to-end Thrift example

### PR DESCRIPTION
**Pull request by breerly**
This is a tiny >70 line example showing how to setup and use YARPC+Thrift.

I created this after realizing we had no examples with both client and server in the same app. This example attempts to model the most common use-case of YARPC - creating an app with some procedures and clients.

@yarpc/golang

### CODE REVIEW

**Comment by abhinav** [comment]
You checked the binary `hello` in as well. Remove and .gitignore.

**Comment by breerly** [comment]
@abhinav good catch :) removed

**Comment by abhinav** [comment]
LGTM

**Comment by kriskowal** [comment]
:100: lgtm

**Pull request merged**
