### PR TITLE
glide: Move gomock and testify to testImport

### PR DESCRIPTION
**Pull request by abhinav**
Not entirely sure why they were in the wrong section.

### CODE REVIEW

**Comment by abhinav** [comment]
I don't understand. These are testing-only dependencies.

The only mention of gomock outside of test files and `*test` packages (which
are meant exclusively for testing) is in the code that generates client mocks.
There's no compile time dependency.

```
$ rg -l mock/gomock | grep -v _test.go | grep -v test/
encoding/thrift/thriftrw-plugin-yarpc/gomock.go
```

Same applies to testify.

```
$ rg -l testify | grep -v _test.go | grep -v test/
glide.lock
glide.yaml
transport/x/cherami/example/client.go
transport/x/cherami/mocks/mock_cherami_consumer.go
transport/x/cherami/mocks/mock_cherami_publisher.go
transport/x/cherami/mocks/mock_cherami_factory.go
```

**Comment by abhinav** [comment]
By putting it in import, you're essentially saying that anyone that uses YARPC
can only use compatible versions of testify and gomock which is completely
nonsensical.

```
[elsewhere] $ glide up
...
[ERROR] Failed to generate lock file: Generating lock produced conflicting versions of github.com/stretchr/testify. import (^1.1.3), testImport (master)
```

**Comment by abhinav** [comment]
ping @peter-edge

**Comment by peter-edge** [comment]
We can discuss tomorrow. Stuff in non test go files is able to be imported
by other libraries, you're arbitrarily deciding what you consider test and
not.

**Pull request merged**
