### PR TITLE
Add repo tags to glide.yaml

### PR DESCRIPTION
**Pull request by peter-edge**
Trying to help fix https://github.com/yarpc/yarpc-go/issues/864

### CODE REVIEW

**Comment by abhinav** [comment]
Is this actually the issue from #864? I was seeing that error too and it was for `https://golang.org/x/tools` which doesn't look like it has changed?

**Comment by peter-edge** [comment]
There's no good way to lock that down I think, unless I make it an explicit dependency (instead of implicit). We can do that as we see flaky endpoints, but it's not "proper".

**Comment by peter-edge** [comment]
Note that the issue generally seems to be custom import paths, so I'm just locking down the custom import paths we specify in glide.yaml here, it's a step in the "right" direction

**Comment by peter-edge** [comment]
Note that `go.uber.org` import paths have never failed, the ones that fail are `golang.org` and `google.golang.org` import paths. I know that Google makes you do the `go-get=1` parameter on http gets of the endpoint, so this could be the issue with glide, that glide isn't handling this properly.

**Comment by peter-edge** [comment]
This doesn't fully fix the problem, going to find a better solution.

**Pull request closed without merging**
