### PR TITLE
add AllHeader() function to get all request headers

### PR DESCRIPTION
**Pull request by serggp**
This PR add _AllHeaders()_ function which returns all request headers as a map.

### CODE REVIEW

**Comment by kriskowal** [comment]
Can you tell us more about your use case? We deliberately omitted this API because we were sure it would be overused and felt a small speed bump (using HeaderNames() and Header()) would encourage folks to reason through why they wanted to allocate a map to view all of the headers of a request at the encoding layer.

At this layer, the headers are effectively read-only and there are few cases where it would be beneficial to allocate a map to have a snapshot of the internal structure.

At the transport layer, including middleware, particularly middleware, it’s much more common and valid to, say, replicate headers from an inbound call and forward all of them to an outbound call.

**Comment by serggp** [comment]
I have a handler level logic which sends all the received headers to a downstream service. So it's not middleware stuff. Currently I can use only HeaderNames() which is ineffective since it involves sorting I don't need.

I decided to make a copy of the map when I saw an uppercase comment _"The returned map MUST NOT be changed."_ which is pretty easy to miss. So getting the map and modifying it (for whatever reason) is safe.

**Comment by kriskowal** [comment]
> I have a handler level logic which sends all the received headers to a downstream service. So it's not middleware stuff. Currently I can use only HeaderNames() which is ineffective since it involves sorting I don't need.
> 
> I decided to make a copy of the map when I saw an uppercase comment _"The returned map MUST NOT be changed."_ which is pretty easy to miss. So getting the map and modifying it (for whatever reason) is safe.

Is there a particular reason that the set of headers you’re forwarding is open-ended and not part of the contract for the particular method expressed by the receiving server?

**Comment by serggp** [comment]
> Is there a particular reason that the set of headers you’re forwarding is open-ended and not part of the contract for the particular method expressed by the receiving server?

Handler level logic sends headers as is. It doesn't inspect those headers and is completely unaware of a protocol. It's like a proxy.

**Comment by kriskowal** [comment]
> > Is there a particular reason that the set of headers you’re forwarding is open-ended and not part of the contract for the particular method expressed by the receiving server?
> 
> Handler level logic sends headers as is. It doesn't inspect those headers and is completely unaware of a protocol. It's like a proxy.

Can this problem be better served with a router middleware? Router middleware exists before any other inbound middleware and can forward any procedure, even procedures that the proxy was not compiled with foreknowledge of. At that layer, your proxy would be completely unaware of the payload contents and can forward without the effort of decoding the body. The limitation is that all routing decisions must be informed by headers.

I apologize for being pedantic, but as you can see, omitting this method was intended to give us an opportunity to have this kind of discussion and is very useful for driving awareness of all the options.

**Comment by serggp** [comment]
I see nothing rather than decision making driven by personal preferences here. And these preferences are based on contradiction: there is a function to get all header names, I can get **all the headers** using it. If the preference it to prevent getting all headers, get _HeaderNames()_ shouldn't exist and has to be removed.

I see no point in further discussion. Closing the PR.

**Comment by kriskowal** [comment]
Sorry for the push back. I should emphasize this API was a team decision!

**Comment by Mariachin89** [comment]
Its ok im new to This just trying yo be like u pros.lol. trying to recover a deletread whats app account for sgomary2526@gmail , anda # 2012070247 new # 2018145423. If u CAN help please feo free thank amd happy holidays to u and ur family

**Pull request closed without merging**
