### PR TITLE
[WIP] tchannel/inbound: tests for inbound, handler, header, and reader.

### PR DESCRIPTION
**Pull request by abhinav**
Not yet ready.

Depends on #62.

[Review on Reviewable](https://reviewable.io/reviews/yarpc/yarpc-go/65)

### CODE REVIEW

**Comment by breerly** [comment]
Looks like there's something reproducably broken in crossdock:

```
FAILED - {yarpc-go map[behavior:echo server:yarpc-go]} - err: invalid character 'o' looking for beginning of value
FAILED - {yarpc-go map[server:yarpc-node behavior:echo]} - err: invalid character 'o' looking for beginning of value
FAILED - {yarpc-go map[server:yarpc-java behavior:echo]} - err: invalid character 'o' looking for beginning of value
FAILED - {yarpc-go map[server:yarpc-python behavior:echo]} - err: invalid character 'o' looking for beginning of value
```

Suggest re-running locally with `docker-compose up` to see what blew up.

Since `yarpc-go:echo:yarpc-go` is blowing up, doing #33 would have revealed this.

**Comment by breerly** [comment]
Is this ready for review?

**Comment by abhinav** [comment]
No. Tests for outbound are pending.

**Comment by abhinav** [comment]
Closing in favor of #70 against master.

**Pull request closed without merging**
