### PR TITLE
Skip TChannel tracer tests

### PR DESCRIPTION
**Pull request by peter-edge**
I don't know how you feel about this so feel free to reject and close it, but I think we should do this for now, and keep the issue open.

### CODE REVIEW

**Comment by kriskowal** [comment]
This is a tough call. We can’t allow this feature to regress. It’s also not obvious how to make it not flap. Do you have output for this test flap?

**Comment by peter-edge** [comment]
See this https://github.com/yarpc/yarpc-go/issues/854 (I didn't want to link it so that it wouldn't get auto-resolved).

You could maybe make a change to TChannel and make this work, but then we want a new release of TChannel etc.

**Comment by akshayjshah** [comment]
I'd prefer to try landing #876 before we do this.

**Comment by peter-edge** [comment]
Should I merge? @kriskowal

**Comment by kriskowal** [comment]
@peter-edge If you can get a second review, e.g., @akshayjshah.

**Pull request merged**
