### PR TITLE
Make local.mk's test function depend on deps

### PR DESCRIPTION
**Pull request by willhug**

### CODE REVIEW

**Comment by abhinav** [comment]
context?

**Comment by breerly** [comment]
@willhug can you provide the background and motivation here?

**Comment by willhug** [comment]
Hmm... I was possibly mislead by the docker.mk file that does this automatically.
```
.PHONY: test
test: deps ## run all tests
	PATH=$$PATH:$(BIN) docker run $(DOCKER_RUN_FLAGS) $(DOCKER_IMAGE) make test
```
I made the assumption that this would be advantageous for local tests (especially when switching branches)

I ran into this when I had a rebuild of my thrift/proto files which took a significant amount of time, and after all the wait, the test simply failed because of a missing dep.

I'm fine leaving dropping this if people are against it.

**Comment by peter-edge** [comment]
Docker has a different requirement here, it has to build the image first,
that's why it's different.

I'm going to try to run a test to see if checking in vendor will work with
regards to library code, this would solve a lot of this.

**Pull request closed without merging**
