### PR TITLE
Implement TChannel Transport

### PR DESCRIPTION
**Pull request by abhinav**
This implements the TChannel transport without tests. Posting to get early comments.

Notes:

- This depends on the most recent tchannel-go/dev branch (which hasn't been released yet). We're using glide, though, so it's fine.
- The Inbound and Outbound expect an existing Channel to be passed in. It may be possible to make them construct their own and share it with some internal interface changes. For now, though, because the transport is inside the `tchannel` package, you have to do a qualified import so that you can use the regular `tchannel` package to build a Channel to pass into the Inbound/Outbound.
- JSON and Thrift examples based on the TChannel transport are just copies of the HTTP examples with a difference only in how the RPC object is configured. I might just merge them into a single executable.
- YARPC responses don't currently specify whether there was an application error so the error flag won't be set on the TChannel responses.
- We don't catch panics in handlers right now. We should probably handle that.

[Review on Reviewable](https://reviewable.io/reviews/yarpc/yarpc-go/55)

### CODE REVIEW

**Comment by abhinav** [comment]
@yarpc/golang @yarpc/yarpc

**Comment by abhinav** [comment]
Trying out reviewable for this.

---

Review status: 0 of 25 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-:-KBt6qML20vHa6s25CbN:-1069977903)*

**Comment by breerly** [comment]
ooooo, Reviewable :+1:

**Comment by prashantv** [comment]
Review status: 0 of 25 files reviewed at latest revision, 9 unresolved discussions.

---

*[examples/thrift/keyvalue/tchannel/server/main.go, line 37 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtFkZ6PhFHhWBHpWQd:-KBtFkZ71dpFzwG6aCcU:562327310) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/examples/thrift/keyvalue/tchannel/server/main.go#L37)):*
(applies to all the keyvalue servers) no lock? but what about concurrent requests!

---

*[transport/tchannel/header.go, line 42 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtGLznGfrrcgreAz2v:-KBtGLznGfrrcgreAz2w:348569558) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/header.go#L42)):*
nit: no need to do `make`, `ReadJSON` will create a map if required so you can just do `var headers transport.Headers`

---

*[transport/tchannel/header.go, line 115 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtGkV50sQM0D4z56yz:-KBtGkV50sQM0D4z56z-:1910141294) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/header.go#L115)):*
nit: `[]byte(k)` will do a cast, but if you pass it as a string, you can actually copy the string into the byte slice directly, and that should avoid allocs:
http://play.golang.org/p/AC0cOKJeqc

---

*[transport/tchannel/inbound.go, line 72 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtHB1JXPbWXDwDVTxY:-KBtHB1JXPbWXDwDVTxZ:-447253068) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/inbound.go#L72)):*
Should `Start` override the handler if one's already set? Or should it do nothing or maybe even fail?

---

*[transport/tchannel/inbound.go, line 82 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtHwi6yQ4d_iTyO5mH:-KBtHwi6yQ4d_iTyO5mI:1553204686) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/inbound.go#L82)):*
do we want to use `tchannel.ListenIP` if the user has not specified a specific host?  listening on all interfaces and sending addresses like `[]:0` won't make Hyperbahn happy

---

*[transport/tchannel/inbound.go, line 183 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtJPfQHFrgHxUeTnz7:-KBtJPfRYfxIKK5QnOvO:-1417714687) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/inbound.go#L183)):*
nit: inline into if below

---

*[transport/tchannel/inbound.go, line 189 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtJUFt7MUtLSli7rK3:-KBtJUFt7MUtLSli7rK4:290885969) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/inbound.go#L189)):*
something to think about: if we fail to get a writer, we might want to remember the error rather than calling `Arg3Writer` repeatedly.

---

*[transport/tchannel/inbound.go, line 200 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtJfuTFnycUbJN5YB1:-KBtJfuTFnycUbJN5YB2:1493478684) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/inbound.go#L200)):*
Close doesn't return error?

---

*[transport/tchannel/outbound.go, line 75 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtJySfrabNvRROMzJK:-KBtJySfrabNvRROMzJL:-1953225469) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/outbound.go#L75)):*
you don't want to add peers on every call. does each outbound only apply for a specific service? we should get the subchannel + add peer once.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yarpc/yarpc-go/55)*

**Comment by abhinav** [comment]
Review status: 0 of 25 files reviewed at latest revision, 9 unresolved discussions.

---

*[examples/thrift/keyvalue/tchannel/server/main.go, line 37 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtFkZ6PhFHhWBHpWQd:-KBtSg_iBHZAeT5Hf4iL:-499146009) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/examples/thrift/keyvalue/tchannel/server/main.go#L37)):*
Done.

---

*[transport/tchannel/header.go, line 42 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtGLznGfrrcgreAz2v:-KBtSrLmve9cn0eVZvAX:-499146009) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/header.go#L42)):*
Done.

---

*[transport/tchannel/header.go, line 115 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtGkV50sQM0D4z56yz:-KBtSzZouzX1FRH4Upsy:-499146009) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/header.go#L115)):*
Done.

---

*[transport/tchannel/inbound.go, line 72 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtHB1JXPbWXDwDVTxY:-KBtT7bFUIpJK3MWFNPl:-1339393321) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/inbound.go#L72)):*
Part of the interface is that implementations may assume that `Start` is already called once:

```go
	// Starts accepting new requests and dispatches them to the given Handler.
	//
	// The function MUST return immediately, although it SHOULD block until
	// the inbound is ready to start accepting new requests.
	//
	// Implementations can assume that this function is called at most once.
	Start(handler Handler) error
```

---

*[transport/tchannel/inbound.go, line 82 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtHwi6yQ4d_iTyO5mH:-KBtV9u6HMwUVbw-zBnE:446484805) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/inbound.go#L82)):*
Sounds reasonable. Done.

---

*[transport/tchannel/inbound.go, line 183 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtJPfQHFrgHxUeTnz7:-KBtVY1riXUKA-ILUrYa:-499146009) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/inbound.go#L183)):*
Done.

---

*[transport/tchannel/inbound.go, line 189 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtJUFt7MUtLSli7rK3:-KBtVw9AHSlBcIq6wZxo:778570693) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/inbound.go#L189)):*
Good idea. Done.

---

*[transport/tchannel/inbound.go, line 200 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtJfuTFnycUbJN5YB1:-KBtW64LfhSyRSZ8HT62:436097296) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/inbound.go#L200)):*
I figured since it's almost always being `defer`red, returning an error wasn't required since at that point you really just care about the cleanup. Does the `Arg{Reader,Writer}.Close` method do a lot of heavy lifting with error cases that we actually care about?

---

*[transport/tchannel/outbound.go, line 75 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtJySfrabNvRROMzJK:-KBtWcBwJxsWOvQDeWgR:2018305314) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/outbound.go#L75)):*
Outbounds are not scoped to a single service. They will send all requests.

Yeah, I wasn't sure about this. What's a good way to send a request through a specific peer? Get the peer and set the Service name manually? That probably loses some information that the SubChannel cares about. Alternatively, I could just keep track of which SubChannels have already had the peer added to them.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yarpc/yarpc-go/55)*

**Comment by prashantv** [comment]
Reviewed 25 of 31 files at r1, 5 of 6 files at r2.
Review status: 24 of 25 files reviewed at latest revision, 13 unresolved discussions.

---

*[examples/json/http/server/main.go, line 80 \[r2\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtb1p_J5SgDGUvU-u-:-KBtb1p_J5SgDGUvU-u0:-1221013331) ([raw file](https://github.com/yarpc/yarpc-go/blob/5384e0cc320898d4c346a043c127dd0724265a8d/examples/json/http/server/main.go#L80)):*
nit: use pointers to handler, and embed mutex instead.

---

*[transport/tchannel/header.go, line 100 \[r2\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtiF7vDEPsANNemtEa:-KBtiF7vDEPsANNemtEb:1387679208) ([raw file](https://github.com/yarpc/yarpc-go/blob/5384e0cc320898d4c346a043c127dd0724265a8d/transport/tchannel/header.go#L100)):*
`len(hs) == 0` covers both cases

---

*[transport/tchannel/inbound.go, line 72 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtHB1JXPbWXDwDVTxY:-KBtihBOYAUy6h40zRSJ:98911984) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/inbound.go#L72)):*
"already called once" -> "only once"?

Either way, first do the `ChannelListening` check before you do anything else.

---

*[transport/tchannel/inbound.go, line 82 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtHwi6yQ4d_iTyO5mH:-KBtittAdwPVnod7E1cN:-6398999) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/inbound.go#L82)):*
if they specify ":9000" we probably want to change that to `ListenIP() + ":9000"`, feel free to put a TODO for that case though.

---

*[transport/tchannel/outbound.go, line 75 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtJySfrabNvRROMzJK:-KBtjMNm_W6vVs5ztRxs:1405750950) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/outbound.go#L75)):*
There's another trick which is to start a call using the channel's `BeginCall` method rather than a subchannel. 

That doesn't add the peer to any list, and you specify teh host:port and service in the BeginCall.

Ideally we use that same interface in all cases, but right now it requires a `HostPort`. We should change tchannel to treat blank host:port as "use the subchannel".

---

*[transport/tchannel/outbound.go, line 83 \[r2\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtjuozDzNDw4f2p2Ri:-KBtjuozDzNDw4f2p2Rj:-1893794503) ([raw file](https://github.com/yarpc/yarpc-go/blob/5384e0cc320898d4c346a043c127dd0724265a8d/transport/tchannel/outbound.go#L83)):*
update TODO, `TODO: Set TimeoutPerAttempt in the context's retry options if TTL is set`

---

*[transport/tchannel/outbound.go, line 116 \[r2\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtk2sbL4uDyEQ_tIJb:-KBtk2sbL4uDyEQ_tIJc:1003545747) ([raw file](https://github.com/yarpc/yarpc-go/blob/5384e0cc320898d4c346a043c127dd0724265a8d/transport/tchannel/outbound.go#L116)):*
why underscore in the name?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yarpc/yarpc-go/55)*

**Comment by prashantv** [comment]
*[transport/tchannel/header.go, line 90 \[r3\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBuDXEQupYMoki4d0TB:-KBuDXEQupYMoki4d0TC:-500892) ([raw file](https://github.com/yarpc/yarpc-go/blob/2deaadd4e903ae7f695e5452621ec755aa62a90c/transport/tchannel/header.go#L90)):*
Use `Set` so that keys are case insensitive

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yarpc/yarpc-go/55)*

**Comment by abhinav** [comment]
Review status: 9 of 21 files reviewed at latest revision, 14 unresolved discussions.

---

*[examples/json/http/server/main.go, line 80 \[r2\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtb1p_J5SgDGUvU-u-:-KBuBrWUqwJl12G-fY0H:-499146009) ([raw file](https://github.com/yarpc/yarpc-go/blob/5384e0cc320898d4c346a043c127dd0724265a8d/examples/json/http/server/main.go#L80)):*
Done.

---

*[transport/tchannel/header.go, line 100 \[r2\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtiF7vDEPsANNemtEa:-KBuFwJPL1GKd0R-NSo3:-499146009) ([raw file](https://github.com/yarpc/yarpc-go/blob/5384e0cc320898d4c346a043c127dd0724265a8d/transport/tchannel/header.go#L100)):*
Done.

---

*[transport/tchannel/header.go, line 90 \[r3\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBuDXEQupYMoki4d0TB:-KBuHW9mGKMLu8HmevkB:-499146009) ([raw file](https://github.com/yarpc/yarpc-go/blob/2deaadd4e903ae7f695e5452621ec755aa62a90c/transport/tchannel/header.go#L90)):*
Done.

---

*[transport/tchannel/inbound.go, line 72 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtHB1JXPbWXDwDVTxY:-KBuFzVGvZf78ujGWRak:-1047923149) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/inbound.go#L72)):*
Yeah, I meant "only once".

Based on offline discussion: This is here because we want to allow for the case where you start the Channel first by hand and then call RPC.Start().

This does mean that `i.addr` still needs to be updated. Updating.

---

*[transport/tchannel/inbound.go, line 82 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtHwi6yQ4d_iTyO5mH:-KBuHLhbJlSi2vZ7E7vK:-1143194037) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/inbound.go#L82)):*
Added TODO

---

*[transport/tchannel/outbound.go, line 75 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtJySfrabNvRROMzJK:-KBuFL1PNpPRr13_-_qs:-260296882) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/outbound.go#L75)):*
Switched to Channel.BeginCall when HostPort is given and SubChannel.BeginCall otherwise.

---

*[transport/tchannel/outbound.go, line 83 \[r2\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtjuozDzNDw4f2p2Ri:-KBuDgR10M5UuEDoes4c:-499146009) ([raw file](https://github.com/yarpc/yarpc-go/blob/5384e0cc320898d4c346a043c127dd0724265a8d/transport/tchannel/outbound.go#L83)):*
Done.

---

*[transport/tchannel/outbound.go, line 116 \[r2\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtk2sbL4uDyEQ_tIJb:-KBuFjpjhaIZRJtdfRm6:1674599258) ([raw file](https://github.com/yarpc/yarpc-go/blob/5384e0cc320898d4c346a043c127dd0724265a8d/transport/tchannel/outbound.go#L116)):*
I was originally using it as a "file-local" marker but then I ended up without that for most of the functions in the file. Removing.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yarpc/yarpc-go/55)*

**Comment by prashantv** [comment]
lgtm

---

Review status: 6 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[transport/tchannel/inbound.go, line 200 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtJfuTFnycUbJN5YB1:-KBvJWsyKJOntbuI8qh2:1059460337) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/inbound.go#L200)):*
Close is what will actually flush the body, so Write will usually write to the buffer in the frame and return. Close will probably get the error if the underlying connection closes etc. It'll be useful at least for logging etc.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-:-KBv_yEadZW6LDvdB-BT:677819321)*

**Comment by abhinav** [comment]
Review status: 6 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[transport/tchannel/inbound.go, line 200 \[r1\]](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-KBtJfuTFnycUbJN5YB1:-KBxpulMIa0W3nMRBwyo:-758033030) ([raw file](https://github.com/yarpc/yarpc-go/blob/fdeb440447d7cc11db943c40181752901a0d3c8e/transport/tchannel/inbound.go#L200)):*
Makes sense. Added error to `Close` and a TODO to log it in the caller.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yarpc/yarpc-go/55)*

**Comment by prashantv** [comment]
:lgtm_strong: 

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yarpc/yarpc-go/55#-:-KBxrW6yxA2JhJblgScB:-1868698381)*

**Pull request merged**
