### PR TITLE
crossdock: Implement test subject (server)

### PR DESCRIPTION
**Pull request by abhinav**
This implements the echo endpoints of the Crossdock Test Subject as per
https://github.com/yarpc/yarpc/blob/master/test-subject.md.

---

This includes very basic unit tests of the procedure implementations. I'm working on the client and the behaviors that call these methods. Once those are done, we'll be able to have a test that fires up the server and tests the different behaviors.

---
This change is [Review on Reviewable](https://reviewable.io/reviews/yarpc/yarpc-go/74)

### CODE REVIEW

**Comment by abhinav** [comment]
@yarpc/yarpc @yarpc/golang

**Comment by abhinav** [comment]
>  I'm working on the client and the behaviors that call these methods. Once those are done, we'll be able to have a test that fires up the server and tests the different behaviors.

**Comment by breerly** [comment]
Can you append those to this PR? I'd like to see a TDD-approach to PR's where new concrete code is accompanied by tests that exercise it.

**Comment by abhinav** [comment]
I would like to avoid overly large PRs and keep them more self-contained. This change can be reviewed and merged independent of the client-side change without breaking anything. There are unit tests in this change for the specific behavior that was added. The client change will probably have unit tests for the behavior that gets added there, and either that, or a different PR will have integration tests that run both, the server and the client as part of the test suite. I would like to avoid lumping all of those changes into a single PR for the sake of the reviewer.

**Comment by breerly** [comment]
Ooooookayyy :)

:shipthatshit:

**Pull request merged**
