### PR TITLE
encoding/protobuf

### PR DESCRIPTION
**Pull request by peter-edge**
This PR needs a ton of documentation, explanation, work (especially on error handling), and testing, but before I went any further I thought I would put this up. I'll send the beginning of an explanation of what this is, how it works, and what decisions need to be made before doing further work.

Can't emphasize enough that this is nowhere near merge ready.

### CODE REVIEW

**Comment by peter-edge** [comment]
Build is failing because I have not updated glide.lock yet.

**Comment by peter-edge** [comment]
Was just typing up a long thing haha, will finish that and then ya, those things sound good (not as sure on the proto3 part but we will discuss).

**Comment by peter-edge** [comment]
## some explanation

This is an initial attempt at encoding/protobuf. There's a lot of different things going on here.

### packages

#### `encoding/protobuf`

This is the corresponding package to `encoding/thrift` It relies on `github.com/golang/protobuf/proto` to provide basic functionality similar to `encoding/thrift` etc, and the methods should look familiar. Style is a merge of my own style, while staying consistent with `encoding/thrift` to a large degree.


#### `encoding/protobuf/internal`

This is a compiled protobuf package that provides an `internal.Response` type that is serialized across the wire. More on this later

#### `encoding/protobuf/protoc-gen-yarpc-go`

This is the corresponding package to `encoding/thrift/thriftrw-plugin-yarpc`. `protoc` picks up plugins in a similar method to thrift, and actually the golang generator for protobuf is just a golang binary at `github.com/golang/protobuf/protoc-gen-go`. Files outputted have extensions `pb.yarpc.go`, and are generally in the same package as generated `.pb.go` files, which is a typical golang/protobuf standard.

#### `internal/protoplugin`

This is a support package for `protoc-gen-yarpc-go`. It's effectively `github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway` code, but cleaned up, simplified, and put into a library that exposes very little. More on this later.

#### `yarpc.proto`

This defines a yarpc-specific `google.protobuf.MethodOption` field that says what types of application errors that have wrapping protobuf messages are returned per service method. This will probably go away, but I left it in as an option for now.

#### `scripts/protoc-{yarpc-}go.bash`

These are compilation scripts to support using `yarpc.proto`.

#### `api/protobuf`

This is the generated golang protobuf code for `yarpc.proto`.

#### `internal/examples/protobuf-keyvalue`

This is an example of protobuf's usage, including message types for the current application error propogation scheme (more on this later).

#### `make proto-example-run`

Self-explanatory.

### protoc-gen-yarpc-go

There's a few different ways to build a protoc plugin using go:

1. Fork github.com/golang/protobuf, and build in a plugin similar to the grpc plugin in the same repository, and link it similar to https://github.com/golang/protobuf/blob/master/protoc-gen-go/link_grpc.go. You can reuse the generation code at https://github.com/golang/protobuf/blob/master/protoc-gen-go/generator/generator.go with this method.
2. Use the code at https://github.com/grpc-ecosystem/grpc-gateway/tree/master/protoc-gen-grpc-gateway. There's a few plugins that do this, such as https://github.com/tmc/grpcutils/blob/master/protoc-gen-flowtypes/genflowtypes/generator.go
3. Use the code at https://github.com/golang/protobuf/tree/master/protoc-gen-go/plugin directly. A plugin just takes in a serialized `CodeGeneratorRequest` on stdin, and returns a serialized `CodeGeneratorResponse` on stdout.

The benefit of (1) or (2) is that both handle golang imports within generated code, which is a pain to rewrite yourself. Forking golang/protobuf is generally not what you want to do, and the code at grpc-gateway is decent, but a bit dirty in places, and has hard links to dependencies you wouldn't want, along with glog logging. The option I went with was to start with grpc-gateway, clean it up and take out a lot of the stuff I didn't need, and add it as a package here.

The best long-term options are problably either:

- Do a PR for github.com/golang/protobuf that abstracts the code in a way that golang plugins can be added as "sub-plugins", and then abstract the generator code to be more genericd
- Create a go.uber.org/protoplugin, that siginificantly cleans up `internal/protoplugin` and exposes it as it's own library.

### streaming methods

Thrift has no equivalent to protobuf's client-side or server-side streaming methods, and as the transports stand right now, there's no obvious way to add such support in directly. For now, `protoc-gen-yarpc-go` just ignores methods that have either client-side or server-side streaming, but it would be nice if this was supported at the transport layer.

### application error propogation

Protobuf does not have an equivalent concept of an `exception`. Service methods simply have a request type and a response type (which must be messages, not primitivies), and rpc implementations are responsible for the errors themselves. This PR includes one option, an option I think actually should be discarded, but I left it in for now.

Right now, there is a type in `encoding/protobuf` called `ApplicationError`. A protobuf definition can define a message type, such as `ErrNoKeyFound`, and then if it wants to return this on the server side, it can do:

```go
return nil, nil, protobuf.NewApplicationError(&kv.KeyNotFound{Key: key})
```

On the client side, a `*protobuf.ApplicationError` will be returned with this message. I forgot to actually expose the message on this PR, but would add a `GetMessage()` method on `*protobuf.ApplicationError`, but you can see it work with `make proto-example-run`.

How this is actually done is using the `internal.Response` type, which is actually serialized over the wire. It contains the serialized response proto (if not nil), and an error that can either be a generic error message, or a specialized ApplicationError message along with the name of the message, so the client-side can make an instance with reflection.

Additionally, `yarpc.proto` defines a method option that can be added to a service method, defining what specialized messages the rpc will return. Right now, this is not used for any validation etc, but could be in the future, and I wanted to show how we could have special yarpc annotations within protobuf in case there were other options we wanted to add. We can take advantage of such otpions both in `encoding/protobuf` and `protoc-gen-yarpc-go`. Another option was to use `protoc-gen-yarpc-go` to add an `Error` field to any protobuf messages that are used as returned errors on methods, or to have the annotation be on the message level, not the service method level, but I decided against this for a few reasons, one of which is that you can't have a field named `error` after this.

I did all this to match thrift a bit. However, having done this, I would recommend we serialize the actual response over the wire directly, and move errors to be headers (as well as not have any specialized protobuf error messages), because:

- This is what gRPC does. A long-term goal here would be to provide a gRPC transport, and even nicer would be to be compatible with gRPC generated clients as they are now. Using the encoding to encode what amounts to transport-specific code is not a good idea, and really we should expand what a transport can do. `SetApplicationError` for example.
- It makes compiling protobuf files a complete mess, as you need to have `yarpc.proto` and `google/protbuf/descriptor.proto` on your included directories properly, and end-users end up doing this in very different ways.
- It's just not very protobuf-y. We don't need to enforce thrift code on protobuf.

### other notes

- There are two main protobuf packages, `github.com/golang/protobuf` and `github.com/gogo/protobuf`. For a bunch of reasons, I highly recommend staying on what amounts to the stable channel. Happy to discuss.
- There's some crazy reflection going on for application errors, this will obviously have to go away.
- I didn't know how the `.t` files in the examples work, so you'll see my hacky solution.
- I named the packages `protobuf` instead of `proto` so it's less of a pain when using `github.com/golang/protobuf/proto` at the same time.
- Obviously this needs testing, a lot more stuff, bla bla bla. I just didn't want to continue without getting some initial feedback.

**Comment by breerly** [comment]
@peter-edge we're focusing on 1.0 items, will pick these up after that! Thanks for all the attention, this is great stuff.

**Comment by peter-edge** [comment]
closing this because i have a branch now inside yarpc/yarpc-go

**Pull request closed without merging**
