### PR TITLE
Preparing release v1.55.1

### PR DESCRIPTION
**Pull request by gandhikrishna**
- [x] Description and context for reviewers: one partner, one stranger
- [x] Entry in CHANGELOG.md

### CODE REVIEW

**Review by gopalchouhan — APPROVED** [review]
LGTM

**Review by Dogild — CHANGES_REQUESTED** [review]
This should be a new release 1.56.0

**Comment by Dogild** [comment]
> This should be a new release 1.56.0

never mind there are only bug fixes, so we can go with 1.55.1

**Comment by Dogild** [comment]
Please look at comment in https://github.com/yarpc/yarpc-go/pull/2078 - we should address them before doing this release

**Review by Dogild — APPROVED** [review]

**Pull request merged**
