### PR TITLE
Do not allow use of tchannel.ContextWithHeaders

### PR DESCRIPTION
**Pull request by peter-edge**
https://github.com/yarpc/yarpc-go/issues/1149

### CODE REVIEW

**Comment by blampe** [comment]
This is awesome and will definitely help avoid a lot of confusion. Love the helpful error message.

**Comment by klnusbaum** [comment]
Hey folks,

This is causing some problems for us. We have a service called Social Profiles that no longer works because of this change. It has a tchannel handler that (I'm guessing) get's passed a tchannel context. It then forwards this context through to some DOSA code that uses this context to make a YARPC call. All of a sudden a call that was working fine a few weeks ago now errors our with "tchannel.ContextWithHeaders is not compatible with YARPC"

Can someone please advise the best course of action here?

**Comment by peter-edge** [comment]
You need to stop using `tchannel.ContextWithHeaders` and use `yarpc.CallOption` - YARPC will not propagate header set using `tchannel.ContextWithHeaders` properly. Using `tchannel.ContextWithHeaders` resulted in issues for other teams, and it took some investigation to find out that this was the cause.

**Comment by klnusbaum** [comment]
update: chatting with Peter right now. Social-profiles has interfaces generated from it's thrift files that require it's tchannel handler functions to take in a `thrift.Context`. `thrift.Context` [is really just](https://godoc.org/github.com/uber/tchannel-go/thrift#Context) a `tchannel.ContextWithHeaders`.

We're currently chatting about what might be an appropriate solution.

**Comment by klnusbaum** [comment]
closing the loop on this: We're going to start using `tchannel.WithoutHeaders` (introduced in https://github.com/uber/tchannel-go/pull/637) to strip the `ContextWithHeaders` that social profiles gets in from it's generated handler code.

**Pull request merged**
