### PR TITLE
Crossdock echo behaviors

### LINKED ISSUE #73: Implement Crossdock echo behaviors
parent: https://github.com/yarpc/yarpc/issues/17  

TODO:

- [ ] Integrate with thriftrw-go code generation (blocked on https://github.com/thriftrw/thriftrw-go/issues/61)

### PR DESCRIPTION
**Pull request by breerly**
Resolves #73 

- [x] implement echo behaviors
- [x] add `yarpc-java:crossdock-echo-behaviors`
- [x] add `yarpc-node:crossdock-echo-behaviors`
- [x] add `yarpc-python:crossdock-echo-behaviors`

@yarpc/golang

### CODE REVIEW

**Comment by breerly** [comment]
@abhinav FYI, seeing this in travis:

```
0.11s$ make test_ci
goveralls -service=travis-ci -v ./crossdock/... ./transport/... ./examples/... ./sync/... ./encoding/... .
exit status 1: cannot use test profile flag with multiple packages
make: *** [test_ci] Error 1
The command "make test_ci" exited with 2.
```

**Comment by breerly** [comment]
@abhinav @kriskowal @junchaowu node added back, and it works!

**Comment by breerly** [comment]
:shipit:

**Comment by abhinav** [comment]
:shipit: for my changes

**Comment by kriskowal** [comment]
:+1:

**Pull request merged**
